# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [55]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [56]:
print(np.__version__)

1.21.6


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [57]:
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [58]:
print(vec.size)
vec.itemsize

10


8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [59]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [60]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [61]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [62]:
x = np.arange(1,11)
print(x[::-1])

[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [63]:
y = np.arange(0,9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [64]:
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [65]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [66]:
np.random.random((3,3,3))

array([[[0.73074667, 0.06715682, 0.6016972 ],
        [0.89703876, 0.06618231, 0.20708075],
        [0.2114969 , 0.70742828, 0.94101355]],

       [[0.7648282 , 0.20618102, 0.28687262],
        [0.66646734, 0.86375099, 0.14231444],
        [0.9453261 , 0.02821855, 0.1421529 ]],

       [[0.48507957, 0.97034168, 0.46604987],
        [0.27281922, 0.27577739, 0.46805369],
        [0.72789199, 0.09797474, 0.16747627]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [67]:
x = np.random.randint(100,size=[10,10])
print(np.min(x),np.max(x))

4 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [68]:
x = np.random.randint(30)
np.mean(x)

9.0

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [69]:
x2 = np.ones((5,5))
x2[1:-1,1:-1] = 0
print(x2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [70]:
np.pad(x2,((1,1),(1,1)),'constant')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [71]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [72]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [73]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [74]:

np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [75]:
arr = np.arange(4).reshape(2, 2)
rep = (4,4)
np.tile(arr,rep)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [76]:
x = np.random.random((5,5))
min = np.max(x)
max =np.min(x)
mm = max-min
x1 = x - min
x = ((x-min) / (max - min))
print(x)

[[ 0.36191469  0.989389    0.80759765  0.87739014  1.        ]
 [ 0.78166958  0.40989873  0.21338693  0.0915611  -0.        ]
 [ 0.40887177  0.45700161  0.82376079  0.33463007  0.4771107 ]
 [ 0.83158908  0.7014717   0.07162287  0.71667103  0.31069686]
 [ 0.56578693  0.42788481  0.40400287  0.32195525  0.60303431]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [77]:
dt = np.dtype('uint32')

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [78]:
a = np.arange(1,16).reshape(5,3)
b = np.arange(1,7).reshape(3,2)
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [79]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m = (a>=3) & (a<=8)
a[m] *= -1
print(a)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10 11 12]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [80]:
# 9 and 
# 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [81]:
# All except z<z<z are legal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [82]:
# array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [83]:
z = np.random.uniform(10)
print(z)


4.591667936467985


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [84]:
z = np.array([1,2,3,4,5])
x = np.array([10,20,30,40,5])
np.intersect1d(z,x)

array([5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [85]:
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [86]:
#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [87]:
today = np.datetime64('today', 'D') 
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D') 
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today) 
print("Tomorrow:", tomorrow)

Yesterday: 2022-11-14
Today: 2022-11-15
Tomorrow: 2022-11-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [88]:
print(np.arange('2012-07', '2020-08',
                dtype='datetime64[D]'))

['2012-07-01' '2012-07-02' '2012-07-03' '2012-07-04' '2012-07-05'
 '2012-07-06' '2012-07-07' '2012-07-08' '2012-07-09' '2012-07-10'
 '2012-07-11' '2012-07-12' '2012-07-13' '2012-07-14' '2012-07-15'
 '2012-07-16' '2012-07-17' '2012-07-18' '2012-07-19' '2012-07-20'
 '2012-07-21' '2012-07-22' '2012-07-23' '2012-07-24' '2012-07-25'
 '2012-07-26' '2012-07-27' '2012-07-28' '2012-07-29' '2012-07-30'
 '2012-07-31' '2012-08-01' '2012-08-02' '2012-08-03' '2012-08-04'
 '2012-08-05' '2012-08-06' '2012-08-07' '2012-08-08' '2012-08-09'
 '2012-08-10' '2012-08-11' '2012-08-12' '2012-08-13' '2012-08-14'
 '2012-08-15' '2012-08-16' '2012-08-17' '2012-08-18' '2012-08-19'
 '2012-08-20' '2012-08-21' '2012-08-22' '2012-08-23' '2012-08-24'
 '2012-08-25' '2012-08-26' '2012-08-27' '2012-08-28' '2012-08-29'
 '2012-08-30' '2012-08-31' '2012-09-01' '2012-09-02' '2012-09-03'
 '2012-09-04' '2012-09-05' '2012-09-06' '2012-09-07' '2012-09-08'
 '2012-09-09' '2012-09-10' '2012-09-11' '2012-09-12' '2012-09-13'
 '2012-09-

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [90]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [91]:
Z = np.random.uniform(0,10,10)
print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5. 3. 4. 6. 8. 6. 7. 8. 8. 9.]
[5. 3. 4. 6. 8. 6. 7. 8. 8. 9.]
[5. 3. 4. 6. 8. 6. 7. 8. 8. 9.]
[5 3 4 6 8 6 7 8 8 9]
[5. 3. 4. 6. 8. 6. 7. 8. 8. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [92]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [93]:
def generate():
   for n in range(10):
       yield n
nums = np.fromiter(generate(),dtype=float,count=-1)
print("New array:")
print(nums)

New array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [94]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [95]:
x = np.random.random(10)
print(np.sort(x))

[0.12951388 0.32541813 0.33209951 0.40235476 0.40514626 0.43208921
 0.55390567 0.60026024 0.6837326  0.86702563]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [96]:
x = np.random.random(10)
np.add.reduce(x)

5.084372376702478

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [97]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 0 0 1]
Second array:
[1 1 0 1 0 1]
Test above two arrays are equal or not!
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [98]:
x = np.zeros(5)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [99]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.91651176 1.03944972 0.53544428 0.97524359 0.13226693 0.88298056
 0.14937459 0.37074465 0.90418413 0.41804351]
[1.21129793 0.37800259 1.4806082  1.5336923  1.3982673  0.79766952
 0.25588706 1.07366887 1.10216855 0.80026642]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [100]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.73493758 0.58534809 0.962519   0.47134466 0.32444254 0.83530154
 0.15870729 0.81213038 0.74384739 0.11183258]
Maximum value replaced by 0:
[0.73493758 0.58534809 0.         0.47134466 0.32444254 0.83530154
 0.15870729 0.81213038 0.74384739 0.11183258]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [101]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [102]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [103]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [104]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [105]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

44


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [106]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [107]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.40067201 0.75606203 0.48882363 0.8312558  0.49786721
  0.56486554 0.33455411 0.14044435 0.84924515]
 [0.40067201 0.         0.35545214 0.4326793  0.65396741 0.50177366
  0.18967578 0.50257383 0.52691554 0.62416   ]
 [0.75606203 0.35545214 0.         0.64617892 0.68889819 0.72960128
  0.22712273 0.80754486 0.881122   0.6122794 ]
 [0.48882363 0.4326793  0.64617892 0.         0.35044791 0.08388555
  0.59740905 0.25218989 0.51497315 0.39098411]
 [0.8312558  0.65396741 0.68889819 0.35044791 0.         0.38055662
  0.75385979 0.59056582 0.86541885 0.10134046]
 [0.49786721 0.50177366 0.72960128 0.08388555 0.38055662 0.
  0.6732482  0.21109687 0.50061627 0.43803535]
 [0.56486554 0.18967578 0.22712273 0.59740905 0.75385979 0.6732482
  0.         0.69165336 0.69938835 0.70131092]
 [0.33455411 0.50257383 0.80754486 0.25218989 0.59056582 0.21109687
  0.69165336 0.         0.30115918 0.64133528]
 [0.14044435 0.52691554 0.881122   0.51497315 0.86541885 0.50061627
  0.69938835 0.301159

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [108]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[74 60 48 21 24 71  4 81  5 27]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [112]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5,6,  ,  , 7, 8,  , 9,10,11''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[ 1  2  3  4  5  6 -1 -1  7  8 -1  9 10 11]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [113]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [114]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [115]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [116]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.46025909  0.06591289 -0.41623653  0.35607921 -0.16587603  0.21310946
  -0.33473766 -0.27664071 -0.0819991   0.18012937]
 [ 0.09692879 -0.35766795 -0.5220936  -0.19543713 -0.12826624  0.01920829
   0.24288465  0.29886788  0.32365026  0.22192504]
 [-0.17370658  0.00378454  0.23951598  0.19987358  0.02201865 -0.08850854
  -0.37108244 -0.14058587 -0.03455524  0.34324593]
 [-0.33629847  0.03513666  0.19247498  0.34597993 -0.44774221  0.00965723
  -0.04605386 -0.00235716  0.4047523  -0.15554939]
 [-0.05374107  0.22488167 -0.17963423 -0.15104372  0.21744656  0.09399319
  -0.17170848 -0.49659787  0.365609    0.15079495]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [117]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 2 2]
 [6 6 9]
 [1 9 8]]
[[0 2 2]
 [6 6 9]
 [1 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [118]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [119]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.45094487947339434


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [120]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [121]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [122]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[5. 3. 4. 1. 1. 3. 6. 1. 3. 3.]
[ 9.  5.  7.  1.  1.  5. 11.  1.  5.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [123]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [124]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [125]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 57 62 53]
 [52 60 60 64]
 [71 50 52 55]]
[[47 57 62 53]
 [52 60 60 64]
 [71 50 52 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [126]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49334316 0.49702901 0.67971133 0.44005256 0.57725601 0.529147
 0.30709856 0.27958061 0.44988928 0.49183539]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [127]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.43794647, 1.0030235 , 0.78373643, 0.79058632, 1.22075444])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [128]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [129]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [130]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [131]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 15) ( 2, 34) ( 2, 36) ( 2, 72) ( 2, 77) ( 2, 98) ( 8, 35) ( 8, 86)
 (14, 50) (14, 78) (15, 72) (25, 81) (25, 97) (30, 68) (30, 90) (34, 45)
 (34, 72) (34, 77) (35, 86) (36, 98) (45, 72) (46, 66) (46, 84) (50, 78)
 (57, 66) (57, 76) (66, 76) (66, 84) (68, 90) (81, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [132]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [133]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [134]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [135]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.10678552, -0.7618796 ,  0.034187  ,  0.06021304, -0.64896314,
       -0.1908541 ,  0.85191611, -0.74587701,  0.84194762,  0.47657413,
        0.56345936,  0.90878104, -0.58379389, -0.40476665,  0.89486608,
       -0.05951709,  0.02331246,  0.29821396, -0.75770254, -0.99981255,
        0.5537088 ,  0.95367357, -0.95630076,  0.85258507, -0.22822913,
        0.06580406,  0.40786223, -0.89198964,  0.85538529,  0.2262748 ,
       -0.97711727,  0.2907403 ,  0.55803036,  0.04291371, -0.61899479,
       -0.2162523 , -0.7513731 ,  0.67135754,  0.33900096, -0.79131102,
       -0.97946131,  0.99471615, -0.04209643, -0.1612323 , -0.77908353,
       -0.05486506, -0.40751748,  0.97748222, -0.88853034,  0.65420373,
        0.55840772,  0.78183767,  0.40226909,  0.28617012,  0.40928912,
        0.07785908, -0.3254693 ,  0.35386043,  0.41409599, -0.69420915,
        0.6472735 ,  0.59956174, -0.73837095,  0.29390483, -0.66120769,
        0.29615257,  0.09641428,  0.7299235 ,  0.02764962,  0.29

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [136]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.65913454 11.37206866 11.50300277  0.9262994   4.68248713  3.97541686
 10.79777867 15.09777159  9.45122842  3.99923698]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [137]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.7578725   0.16893908  8.05550059  7.18164996  2.30240785 12.78462768
   1.34430161  0.91789105 14.45471696  0.47308983]
 [ 7.31583041  5.11753233  0.59139371  5.42778033  9.79866172  0.88863908
   9.4977856  13.50484549  2.45175937  4.24618852]
 [ 7.50264932  0.99407057  8.50275788  6.49957009  1.37054482 12.6045142
   1.42678381  1.62964083 14.23982636  0.86347692]
 [ 9.33662488  7.97108041  3.55247967  7.22272042 10.99690979  1.68096307
  12.30612191 15.23818272  0.0782493   2.8733074 ]
 [12.03875427  2.46806594  6.18073843  8.05341411  3.88832142 12.35489655
   0.28615235  0.03578124 14.1107229   3.72131189]
 [ 3.34991469  2.70250255  8.4816183   2.30553828  3.51956074 10.09357651
   0.09215288  5.91256482 11.60285389  5.80693538]
 [ 5.15506532  3.72610845 11.08609071  7.47896604  1.73112442 14.49663413
   3.66658325  0.71652079 16.0796835   2.75608073]
 [10.19357032  2.91127501  4.4046856   3.90924863  0.41175163  8.98495558
   2.49794555  4.13697368 10.67185679  0.91078727]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [138]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 7 2 5 6 0 5 5 2 6]
 [4 7 7 6 0 5 3 8 2 7]
 [6 8 2 7 1 0 2 3 4 4]
 [5 0 5 2 1 8 8 3 6 9]
 [0 8 4 6 2 7 8 6 2 7]
 [8 8 1 1 8 7 5 5 8 3]
 [6 7 7 7 1 7 1 0 6 4]
 [2 1 7 2 3 1 6 7 1 9]
 [0 3 5 7 3 7 8 7 0 5]
 [5 8 6 4 8 2 9 4 0 5]]
[[0 0 0 0 0]
 [0 0 7 2 5]
 [0 4 7 7 6]
 [0 6 8 2 7]
 [0 5 0 5 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [139]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [140]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [141]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [142]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 0]
   [4 0 1]
   [3 3 3]]

  [[4 0 4]
   [0 1 3]
   [3 3 3]]

  [[0 4 3]
   [1 3 0]
   [3 3 2]]

  [[4 3 2]
   [3 0 2]
   [3 2 1]]

  [[3 2 2]
   [0 2 1]
   [2 1 4]]

  [[2 2 0]
   [2 1 1]
   [1 4 3]]

  [[2 0 3]
   [1 1 2]
   [4 3 0]]

  [[0 3 2]
   [1 2 2]
   [3 0 2]]]


 [[[4 0 1]
   [3 3 3]
   [3 2 3]]

  [[0 1 3]
   [3 3 3]
   [2 3 4]]

  [[1 3 0]
   [3 3 2]
   [3 4 1]]

  [[3 0 2]
   [3 2 1]
   [4 1 4]]

  [[0 2 1]
   [2 1 4]
   [1 4 0]]

  [[2 1 1]
   [1 4 3]
   [4 0 3]]

  [[1 1 2]
   [4 3 0]
   [0 3 3]]

  [[1 2 2]
   [3 0 2]
   [3 3 2]]]


 [[[3 3 3]
   [3 2 3]
   [1 2 4]]

  [[3 3 3]
   [2 3 4]
   [2 4 0]]

  [[3 3 2]
   [3 4 1]
   [4 0 0]]

  [[3 2 1]
   [4 1 4]
   [0 0 4]]

  [[2 1 4]
   [1 4 0]
   [0 4 1]]

  [[1 4 3]
   [4 0 3]
   [4 1 3]]

  [[4 3 0]
   [0 3 3]
   [1 3 2]]

  [[3 0 2]
   [3 3 2]
   [3 2 0]]]


 [[[3 2 3]
   [1 2 4]
   [4 1 0]]

  [[2 3 4]
   [2 4 0]
   [1 0 1]]

  [[3 4 1]
   [4 0 0]
   [0 1 2]]

  [[4 1 4]
   [0 0 4]
   [1 2 2]]

  [[1 4 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [143]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  8  8  6  7]
 [ 8  0 15  2  2]
 [ 8 15  3 42 12]
 [ 6  2 42  8 12]
 [ 7  2 12 12  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [144]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [145]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [146]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [147]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [148]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [149]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [150]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.77 s ± 18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
138 ms ± 859 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
115 ms ± 856 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [151]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [152]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 2 0]
 [2 2 2]
 [0 1 1]
 [3 4 4]
 [4 1 4]
 [2 1 1]
 [1 4 0]
 [1 2 4]
 [0 1 2]
 [2 2 3]]
[[2 2 0]
 [0 1 1]
 [3 4 4]
 [4 1 4]
 [2 1 1]
 [1 4 0]
 [1 2 4]
 [0 1 2]
 [2 2 3]]
[[2 2 0]
 [0 1 1]
 [3 4 4]
 [4 1 4]
 [2 1 1]
 [1 4 0]
 [1 2 4]
 [0 1 2]
 [2 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [153]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [154]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [155]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.3069736 , 0.33299576, 0.40824092, 0.23191914, 0.36380291,
        0.33099857, 0.44346741, 0.26644179, 0.42309735, 0.30065029],
       [0.34209851, 0.37109821, 0.45495316, 0.25845607, 0.40543041,
        0.36887249, 0.49421037, 0.29692892, 0.47150951, 0.33505166],
       [0.00823848, 0.00893686, 0.01095627, 0.00622419, 0.00976365,
        0.00888326, 0.01190167, 0.0071507 , 0.01135498, 0.00806878],
       [0.39206438, 0.42529969, 0.52140224, 0.29620539, 0.46464635,
        0.42274889, 0.56639325, 0.34029746, 0.54037676, 0.38398829],
       [0.31919149, 0.34624936, 0.42448936, 0.24114978, 0.37828267,
        0.34417268, 0.4611179 , 0.27704647, 0.43993709, 0.3126165 ],
       [0.55222385, 0.59903589, 0.73439662, 0.41720617, 0.65445578,
        0.59544308, 0.79776659, 0.47930999, 0.76112228, 0.54084866],
       [0.52971428, 0.57461817, 0.70446137, 0.40020014, 0.62777905,
        0.57117182, 0.76524827, 0.4597725 , 0.73009765, 0.51880275],
       [0.01830578, 0.01985756, 0.0243446

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [156]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [157]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [158]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.27728065  0.08957908]
